repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: "v0.14.3"
    hooks:
      - id: ruff

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      # Generic
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: fix-byte-order-marker
      # - id: check-shebang-scripts-are-executable
      - id: check-merge-conflict
      - id: check-symlinks
      # Basic syntax checks
      - id: check-ast
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      # Security
      - id: detect-private-key
      # - id: detect-aws-credentials
      # Whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
      # Misc Python
      - id: debug-statements
      - id: forbid-new-submodules
        args: ["--allow-missing-credentials"]
      # - id: check-docstring-first
      # - id: name-tests-test
      # - id: no-commit-to-branch
      # - id: requirements-txt-fixer
# Install pre-commit hooks via
# pre-commit install

# exclude: >
#     (?x)^(
#       \.vscode/settings\.json|
#       tests/.*xml|
#       tests/.*txt|
#     )$

# repos:

#   - repo: https://github.com/pre-commit/pre-commit-hooks
#     rev: v6.0.0
#     hooks:
#     - id: check-merge-conflict
#     - id: trailing-whitespace
#     - id: end-of-file-fixer
#     - id: check-docstring-first
#     - id: check-json
#     - id: check-yaml
#     - id: debug-statements

#   - repo: https://github.com/abravalheri/validate-pyproject
#     rev: v0.24.1
#     hooks:
#       - id: validate-pyproject

#   - repo: https://github.com/psf/black
#     rev: 25.9.0
#     hooks:
#       - id: black

#   - repo: https://github.com/keewis/blackdoc
#     rev: v0.4.5
#     hooks:
#       - id: blackdoc
#         additional_dependencies: ["black==25.1.0"]
#       - id: blackdoc-autoupdate-black

#   - repo: https://github.com/PyCQA/flake8
#     rev: 7.3.0
#     hooks:
#       - id: flake8
#         args: ["--ignore=E704,E203,W503,W605,W293,W291,E501"]

#   - repo: https://github.com/PyCQA/isort
#     rev: 7.0.0
#     hooks:
#       - id: isort

#   - repo: https://github.com/econchick/interrogate
#     rev: 1.7.0  # or master if you're bold
#     hooks:
#       - id: interrogate
#         args: ["-vv", "--fail-under=100", "--omit-covered-files", "--ignore-init-module"]
#         pass_filenames: false  # needed if excluding files with pyproject.toml
