preview = true

lint.select = [
    "ALL",
]

lint.extend-ignore = [
    # Later...
    "ANN", # flake8-annotations
    "D", # pydocstyle
    "DOC",
    "TRY",
    "PLR",
    "ARG",
    "FBT",
    "ERA",
    "A",
    # False positives
    "COM812", #  	[*] missing-trailing-comma
    "T201", #    	[*] print
    "RUF005", # Confusing syntax
    "E501", #    	[ ] line-too-long
    "S101", # use of assert
    "RUF001", #	[ ] ambiguous-unicode-character-string
    "SIM108", # 	if-else-block-instead-of-if-exp
    # FIX or review This
    "S608", # Potential SQL injection
    # Review later
    "SLF001", #	[ ] private-member-access
    "CPY001", #	[ ] missing-copyright-notice
    "PT011", # 	[ ] pytest-raises-too-broad
    "PT021", #  	pytest-fixture-finalizer-callback
    "SIM102", # 	collapsible-if
]

[lint.extend-per-file-ignores]
"benchmarks/**/*.py" = [
    "S311",
]
"examples/**/*.py" = [
    "RUF012",  # Meta class indexed_fields is intentionally mutable class attribute
]
"tests/**/*.py" = [
    "RUF012",  # Meta class indexed_fields is intentionally mutable class attribute
]
